"""Base curada y versionada. Paráfrasis educativas; no reproduce el manual BI-RADS."""
SOURCES={
 "XAI_OCCLUSION":{"title":"Zeiler MD, Fergus R. Visualizing and Understanding Convolutional Networks. arXiv:1311.2901; ECCV 2014","url":"https://arxiv.org/abs/1311.2901","consulted":"2026-09-13"},
 "NCI_MAMMO":{"title":"National Cancer Institute. Mammograms","url":"https://www.cancer.gov/types/breast/screening/mammograms","consulted":"2026-09-13"},
 "RAD_REPORT":{"title":"ACR/RSNA RadiologyInfo. Cómo leer su informe de imágenes del seno","url":"https://www.radiologyinfo.org/es/info/article-breast-imaging-report","consulted":"2026-09-13"},
 "ACS_REPORT":{"title":"American Cancer Society. Understanding Your Mammogram Report","url":"https://www.cancer.org/cancer/types/breast-cancer/screening-tests-and-early-detection/mammograms/understanding-your-mammogram-report.html","consulted":"2026-09-13"},
 "NHS_PAIN":{"title":"NHS. Breast pain: when to get medical help","url":"https://www.nhs.uk/symptoms/breast-pain/","consulted":"2026-09-13"},
 "NHS_LUMP":{"title":"NHS. Breast lumps","url":"https://www.nhs.uk/symptoms/breast-lump/","consulted":"2026-09-13"},
 "NHS_EMERGENCY":{"title":"NHS. Sepsis: symptoms requiring emergency attention","url":"https://www.nhs.uk/conditions/sepsis/","consulted":"2026-09-13"},
 "DESIGN":{"title":"MammoTrace 4.1.0. Regla de diseño académico; requiere validación institucional","url":None,"consulted":"2026-09-13"}
}
# Cada fragmento es breve, utilizable localmente y con procedencia explícita.
BLOCKS={
 "scope":{"title":"Alcance de la explicación","text":"Esta explicación ayuda a comprender términos y preparar preguntas. No sustituye el informe completo ni determina por sí misma un diagnóstico o el tiempo seguro de espera.","sources":["DESIGN"],"tags":["ayuda","explicacion","consulta","espera"]},
 "birads_0":{"title":"BI-RADS 0 · evaluación incompleta","text":"Falta completar la evaluación mediante imágenes adicionales o comparación con estudios previos. No equivale a un resultado negativo ni confirma cáncer. Consulte qué falta y cómo se programa.","sources":["NCI_MAMMO","ACS_REPORT"],"tags":["birads","incompleto","adicionales","cero"]},
 "birads_1":{"title":"BI-RADS 1 · evaluación negativa","text":"El informe no describe hallazgos sospechosos en este examen. Mantenga el seguimiento indicado; un cambio nuevo en la mama necesita valoración aunque el informe sea negativo.","sources":["ACS_REPORT","NHS_LUMP"],"tags":["negativo","normal","uno"]},
 "birads_2":{"title":"BI-RADS 2 · hallazgos benignos","text":"El radiólogo describe hallazgos considerados benignos. El seguimiento se acuerda con el equipo tratante. Esta categoría no elimina la necesidad de consultar por síntomas nuevos.","sources":["ACS_REPORT","NHS_LUMP"],"tags":["benigno","dos","quiste"]},
 "birads_3":{"title":"BI-RADS 3 · probablemente benigno","text":"Se propone vigilancia por imágenes en un intervalo corto. La fecha debe tomarse del informe y de la indicación profesional, no calcularse con la puntuación del modelo.","sources":["RAD_REPORT"],"tags":["probablemente","tres","seguimiento","control"]},
 "birads_4":{"title":"BI-RADS 4 · hallazgo sospechoso","text":"La categoría expresa una sospecha que requiere evaluación diagnóstica y suele motivar una biopsia. No es una confirmación de cáncer. Las subcategorías A, B y C no deben confundirse con un resultado de patología.","sources":["RAD_REPORT","ACS_REPORT"],"tags":["cuatro","sospechoso","biopsia","4a","4b","4c"]},
 "birads_5":{"title":"BI-RADS 5 · sospecha elevada","text":"El informe describe una sospecha elevada y requiere coordinar sin demora los pasos diagnósticos con el equipo tratante. La confirmación corresponde a la evaluación clínica y, cuando procede, a la biopsia.","sources":["RAD_REPORT","NCI_MAMMO"],"tags":["cinco","sospecha","biopsia"]},
 "birads_6":{"title":"BI-RADS 6 · antecedente de biopsia confirmatoria","text":"Esta categoría se utiliza cuando ya existe una malignidad comprobada mediante biopsia. La aplicación no la confirma nuevamente: ayuda a organizar preguntas y continuar el plan del equipo tratante.","sources":["NCI_MAMMO"],"tags":["seis","confirmado","patologia"]},
 "multiple":{"title":"Varios BI-RADS en un documento","text":"Un informe puede incluir categorías para distintas lesiones o menciones de estudios previos. Revise lateralidad, fecha y conclusión. El programa conserva todas las menciones y no elige automáticamente la mayor.","sources":["RAD_REPORT","DESIGN"],"tags":["varios","categorias","anterior","lateralidad","dos"]},
 "density":{"title":"Densidad mamaria","text":"La densidad es una característica descrita por el radiólogo. No debe deducirse de la media de píxeles o del contraste de una captura. Comente con su profesional cómo influye en la interpretación del estudio y en su seguimiento.","sources":["NCI_MAMMO","DESIGN"],"tags":["densidad","densa","densas","tejido"]},
 "biopsy":{"title":"Biopsia y confirmación","text":"Una imagen sospechosa y una biopsia no son lo mismo. La biopsia permite estudiar una muestra de tejido. Pregunte por su indicación, preparación, entrega del resultado y profesional responsable de explicarlo.","sources":["NCI_MAMMO","NHS_LUMP"],"tags":["biopsia","cancer","maligno","confirmacion","tejido"]},
 "new_symptoms":{"title":"Cambios que deben comunicarse","text":"Un bulto nuevo, secreción con sangre, cambios en la piel o retracción reciente del pezón necesitan valoración profesional. Informe cuándo aparecieron y si están cambiando; no espere únicamente una respuesta informática.","sources":["NHS_LUMP"],"tags":["bulto","masa","sangre","secrecion","piel","pezon"]},
 "infection_signs":{"title":"Dolor con inflamación o fiebre","text":"Una mama roja, caliente o hinchada, especialmente con fiebre o escalofríos, requiere atención pronta. El software no determina si la causa es una infección y no recomienda antibióticos por cuenta propia.","sources":["NHS_PAIN"],"tags":["fiebre","roja","caliente","hinchada","dolor","inflamacion"]},
 "emergency":{"title":"No espere ante deterioro importante","text":"Dificultad marcada para respirar, confusión reciente, dificultad para despertar u otro deterioro intenso requieren ayuda urgente. Acuda al servicio de urgencias o al número de emergencias de su localidad; no use esta aplicación para aplazar la atención.","sources":["NHS_EMERGENCY"],"tags":["urgencia","respirar","confusion","desmayo","alarma"]},
 "xai":{"title":"Qué significa el mapa explicable","text":"La oclusión muestra cuánto cambia una activación del modelo al ocultar regiones del tensor. No identifica una lesión, no explica una causa biológica y no convierte etiquetas sintéticas en evidencia clínica.","sources":["XAI_OCCLUSION","DESIGN"],"tags":["mapa","xai","ia","modelo","explicable","imagen"]},
 "planning":{"title":"Preparar la consulta","text":"Lleve el informe, los estudios anteriores disponibles y sus preguntas. Confirme quién revisará el resultado, qué paso está pendiente y qué canal utilizar si aparecen cambios. Una fecha del calendario no certifica que sea seguro esperar hasta entonces.","sources":["DESIGN"],"tags":["cita","esperar","programacion","preparar","consulta","preguntas"]}
}
BIRADS_LABELS={c:BLOCKS['birads_'+c[0]]['title'] for c in ['0','1','2','3','4','4A','4B','4C','5','6']}
